apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: us-central1-docker.pkg.dev/exalate-project-492211/backend-repo/api:v2
          ports:
            - containerPort: 3000
