name: Build ArgoCD Image Updater

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source directly from GitHub
        uses: actions/checkout@v4
        with:
          repository: argoproj/argocd-image-updater
          ref: v0.13.0

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: projects/589047239228/locations/global/workloadIdentityPools/github/providers/github-exalate
          service_account: gha-artifact-writer@exalate-project-492211.iam.gserviceaccount.com

      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v2

      - name: Configure Docker
        run: gcloud auth configure-docker us-central1-docker.pkg.dev

      - name: Build image
        run: |
          docker build -t us-central1-docker.pkg.dev/exalate-project-492211/backend-repo/argocd-image-updater:v0.13.0 .

      - name: Push image
        run: |
          docker push us-central1-docker.pkg.dev/exalate-project-492211/backend-repo/argocd-image-updater:v0.13.0
